apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp
  template:
    metadata:
      labels:
        app: lamp
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/local/apache2/htdocs/
          livenessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: mysql
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 80
      volumes:
        - name: web-content
          hostPath:
            path: /path/to/local/web/content
        - name: mysql-data
          hostPath:
            path: /path/to/local/mysql/data
