apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80
              name: apache
          volumeMounts:
            - name: web-content
              mountPath: /usr/local/apache2/htdocs/
            - name: apache-config
              mountPath: /usr/local/apache2/htdocs/index.html
              subPath: index.html
          livenessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: web-content
          hostPath:
            path: /path/to/local/web/content
        - name: apache-config
          configMap:
            name: apache-config
      restartPolicy: Always

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  index.html: |
    <html>
      <head>
        <title>My Custom Page</title>
      </head>
      <body>
        <h1>Welcome to my custom page!</h1>
      </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: mysql-data
          hostPath:
            path: /path/to/local/mysql/data
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 80
              name: phpmyadmin
          livenessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
