apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  selector:
    app: lamp
  ports:
    - name: apache
      port: 80
      targetPort: 80
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: phpmyadmin
      port: 8080
      targetPort: 8080
